"""Password hash modification 2

Revision ID: 109b75eb433e
Revises: 83136ba0c3f3
Create Date: 2022-05-14 20:04:00.628912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109b75eb433e'
down_revision = '83136ba0c3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vaisefuder', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vaisefuder')
    # ### end Alembic commands ###
