"""empty message

Revision ID: 180b6e748091
Revises: b3f0fde1147b
Create Date: 2022-05-14 20:32:59.731410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180b6e748091'
down_revision = 'b3f0fde1147b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_has', sa.Text(), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_has')
    # ### end Alembic commands ###
