"""empty message

Revision ID: 2be66299ffdd
Revises: a1d35a402154
Create Date: 2022-04-28 23:24:16.291760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2be66299ffdd'
down_revision = 'a1d35a402154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missing_people')
    op.drop_table('users')
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('picture', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('isUserProfile', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('isMissingPersonProfile', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('missing_person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['missing_person_id'], ['missing_people.id'], name='images_missing_person_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='images_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey'),
    sa.UniqueConstraint('picture', name='images_picture_key')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('missing_people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('birthday', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('birthplace', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('place_of_disappearance', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('disappearance_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='missing_people_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='missing_people_pkey')
    )
    # ### end Alembic commands ###
