"""empty message

Revision ID: 3346bf9a69ee
Revises: 0dabfecc2415
Create Date: 2022-04-28 12:41:46.906228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3346bf9a69ee'
down_revision = '0dabfecc2415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usuario')
    op.drop_table('tb_fotos')
    op.drop_table('tb_pessoa_desaparecida')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_pessoa_desaparecida',
    sa.Column('id_p_desaparecida', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('local_nascimento', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('local_desaparecimento', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('detalhes_desaparecimento', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_foto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_foto'], ['tb_fotos.id_foto'], name='fotos_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['tb_usuario.id_usuario'], name='usuario_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_p_desaparecida', name='tb_pessoa_desaparecida_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tb_fotos',
    sa.Column('id_foto', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('is_profile', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('foto', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('id_p_desaparecida', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_p_desaparecida'], ['tb_pessoa_desaparecida.id_p_desaparecida'], name='pessoa_desparecida_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_foto', name='tb_fotos_pkey')
    )
    op.create_table('tb_usuario',
    sa.Column('id_usuario', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('senha', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_usuario', name='tb_usuario_pkey')
    )
    # ### end Alembic commands ###
