"""empty message

Revision ID: 453672142f96
Revises: 3da5e50af08c
Create Date: 2022-05-14 21:34:59.237894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453672142f96'
down_revision = '3da5e50af08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('name', sa.String(length=25), nullable=False))
    op.add_column('images', sa.Column('mimetype', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'mimetype')
    op.drop_column('images', 'name')
    # ### end Alembic commands ###
