"""Password hash modification

Revision ID: 83136ba0c3f3
Revises: 2be66299ffdd
Create Date: 2022-05-14 19:26:59.282466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83136ba0c3f3'
down_revision = '2be66299ffdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=100), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
