"""empty message

Revision ID: a480a91405cd
Revises: ff74c01a7ef0
Create Date: 2022-05-14 22:28:54.050686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a480a91405cd'
down_revision = 'ff74c01a7ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('filename', sa.String(length=25), nullable=False))
    op.add_column('images', sa.Column('mimetype', sa.String(length=15), nullable=False))
    op.drop_column('images', 'name')
    op.drop_column('images', 'mimetyp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('mimetyp', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('name', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    op.drop_column('images', 'mimetype')
    op.drop_column('images', 'filename')
    # ### end Alembic commands ###
