"""empty message

Revision ID: e046bfef7d28
Revises: fc9bd5075099
Create Date: 2022-05-14 20:14:01.291620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e046bfef7d28'
down_revision = 'fc9bd5075099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_haxx', sa.Text(), nullable=False))
    op.drop_column('users', 'tomanocu')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('tomanocu', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'password_haxx')
    # ### end Alembic commands ###
