"""empty message

Revision ID: e8ac3ba0f1d0
Revises: fb8f4f71182d
Create Date: 2022-05-14 23:02:00.864816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ac3ba0f1d0'
down_revision = 'fb8f4f71182d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('filename', sa.String(length=25), nullable=False))
    op.add_column('images', sa.Column('mimetype', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'mimetype')
    op.drop_column('images', 'filename')
    # ### end Alembic commands ###
