"""empty message

Revision ID: fc9bd5075099
Revises: 109b75eb433e
Create Date: 2022-05-14 20:12:06.325270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9bd5075099'
down_revision = '109b75eb433e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tomanocu', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tomanocu')
    # ### end Alembic commands ###
