"""empty message

Revision ID: ff74c01a7ef0
Revises: 453672142f96
Create Date: 2022-05-14 22:28:01.917667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff74c01a7ef0'
down_revision = '453672142f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('mimetyp', sa.String(length=15), nullable=False))
    op.drop_column('images', 'mimetype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('mimetype', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.drop_column('images', 'mimetyp')
    # ### end Alembic commands ###
